"""Sprint 5A domain models for MiroFish Scenario Engine Integration."""

from hashlib import sha256
import json
from typing import Any, Literal
from pydantic import BaseModel, Field


class ScenarioSeedPackage(BaseModel):
    """
    Point-In-Time input seed package for MiroFish simulation.
    Contains strictly evidence claims, macro state, and sector state available at cutoff.
    """
    seed_package_id: str
    as_of_timestamp: str
    material_event_ids: list[str] = Field(default_factory=list)
    evidence_claim_ids: list[str] = Field(default_factory=list)
    macro_state_ids: list[str] = Field(default_factory=list)
    sector_state_ids: list[str] = Field(default_factory=list)
    known_actor_ids: list[str] = Field(default_factory=list)
    causal_graph_version: str = "1.0.0"
    source_document_ids: list[str] = Field(default_factory=list)
    prompt_template_version: str = "5A.1-mirofish-seed-v1"

    @classmethod
    def compute_seed_id(cls, payload: dict[str, Any]) -> str:
        canonical = {k: v for k, v in payload.items() if k != "seed_package_id"}
        sorted_keys = json.dumps(canonical, sort_keys=True, default=str)
        return sha256(sorted_keys.encode("utf-8")).hexdigest()


class MiroFishSimulationRun(BaseModel):
    """
    Manifest of a MiroFish simulation run.
    Contains HTTP service parameters, request/response hashes, and service status.
    Unexposed API parameters explicitly record 'NOT_EXPOSED_BY_SERVICE'.
    """
    simulation_run_id: str
    seed_package_id: str
    mirofish_project_id: str = "NOT_EXPOSED_BY_SERVICE"
    mirofish_graph_id: str = "NOT_EXPOSED_BY_SERVICE"
    mirofish_simulation_id: str = "NOT_EXPOSED_BY_SERVICE"
    requested_at: str
    completed_at: str = ""
    service_version: str = "mirofish-v1.0"
    model_information: str = "NOT_EXPOSED_BY_SERVICE"
    configuration: dict[str, Any] = Field(default_factory=dict)
    random_seed: str = "NOT_EXPOSED_BY_SERVICE"
    prompt_hash: str = ""
    input_checksum: str = ""
    status: Literal["SUCCESS", "SERVICE_OFFLINE_DETERMINISTIC_FALLBACK", "FAILED"] = "SUCCESS"
    raw_report_ids: list[str] = Field(default_factory=list)
    raw_response_checksum: str = ""
    methodology_version: str = "5A.1-mirofish-run-v1"

    @classmethod
    def compute_run_id(cls, payload: dict[str, Any]) -> str:
        canonical = {k: v for k, v in payload.items() if k != "simulation_run_id"}
        sorted_keys = json.dumps(canonical, sort_keys=True, default=str)
        return sha256(sorted_keys.encode("utf-8")).hexdigest()


class ScenarioHypothesis(BaseModel):
    """
    Typed scenario hypothesis generated by MiroFish.
    Always initialized with verification_status = 'UNVERIFIED'.
    Must NOT directly trigger WATCH, BUY, target price, or order placement.
    """
    hypothesis_id: str
    simulation_run_id: str
    scenario_type: Literal["BASE", "BULL", "BEAR", "CONTRARIAN", "TAIL"] = "BASE"
    trigger: str = ""
    actors: list[str] = Field(default_factory=list)
    actions: list[str] = Field(default_factory=list)
    macro_factors: list[str] = Field(default_factory=list)
    sector_effects: list[str] = Field(default_factory=list)
    second_order_effects: list[str] = Field(default_factory=list)
    expected_horizon: str = "MEDIUM_TERM"
    supporting_evidence_ids: list[str] = Field(default_factory=list)
    contradicting_evidence_ids: list[str] = Field(default_factory=list)
    verification_status: Literal["UNVERIFIED", "PARTIALLY_SUPPORTED", "SUPPORTED", "CONTRADICTED", "REJECTED"] = "UNVERIFIED"
    confidence: float = 0.50

    @classmethod
    def compute_hypothesis_id(cls, payload: dict[str, Any]) -> str:
        canonical = {k: v for k, v in payload.items() if k != "hypothesis_id"}
        sorted_keys = json.dumps(canonical, sort_keys=True, default=str)
        return sha256(sorted_keys.encode("utf-8")).hexdigest()


class ScenarioSet(BaseModel):
    """
    Container aggregating all hypotheses generated for a specific cutoff date.
    """
    scenario_set_id: str
    event_id: str = "GENERAL_MACRO_CUTOFF"
    as_of_timestamp: str
    scenario_hypothesis_ids: list[str] = Field(default_factory=list)
    coverage_summary: str = ""
    contradiction_summary: str = ""
    missing_variables: list[str] = Field(default_factory=list)
    methodology_version: str = "5A.1-scenario-set-v1"
    created_at: str = ""

    @classmethod
    def compute_scenario_set_id(cls, payload: dict[str, Any]) -> str:
        canonical = {k: v for k, v in payload.items() if k not in ("scenario_set_id", "created_at")}
        sorted_keys = json.dumps(canonical, sort_keys=True, default=str)
        return sha256(sorted_keys.encode("utf-8")).hexdigest()
